name: GitHub GCC Action Test Action
run-name: ${{ github.actor }} is running assignment test
on: push

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  quarto-check-output:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')" # If it's NOT a tag ref
    container:
      image: python:3.11-slim
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install quarto quarto-cli
      - name: Autograding
        uses: education/autograding@v1
